### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by konrad889** [sptq/Vhagar#58]
Marcin, daj mi admina ;P skasowałem konto niechcący :dancers: 
Twój szef,
Konrad Tomczyk

**Comment by vircung** [comment]
Dziwne, że niechcący skoro przed usunięciem wyświetlane jest pytanie czy jesteś pewien.

**Comment by sptq** [comment]
:D Za karę 10 zdrowasiek i code review na jutro... może się zastanowię :dancers:

**Comment by vircung** [comment]
Z resztą to nie jest miejsce na zgłoszenia do instancji aplikacji tylko do implementacji mechanizmów.
