### ISSUE TITLE
Support for gravatar

### ISSUE THREAD

**Issue by vircung** [sptq/Vhagar#6]
How about to pull user avatars from gravatar if possible ?

http://railscasts.com/episodes/244-gravatar

**Comment by sptq** [comment]
Great idea, but some people may not have set gravatar. In this situation we must add some defaults avatars like in redmine.

**Comment by vircung** [comment]
AFIK gravatar has default one.

**Comment by sptq** [comment]
We can add this feature

**Comment by sptq** [comment]
I will connect this with user profile, in next commit this feature will be added.
